##
 # Author: Neal Gompa
 #
 # Licensed under the GNU General Public License Version 3
 # Fedora-License-Identifier: GPLv3+
 # SPDX-2.0-License-Identifier: GPL-3.0+
 # SPDX-3.0-License-Identifier: GPL-3.0-or-later
 #
 # This is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this.  If not, see <https://www.gnu.org/licenses/>.
##


---
- name: Prepare system for package builds
  become: true
  block:
    - name: Install packaging tools
      ansible.builtin.dnf:
        pkg:
          - "centos-packager"
          - "copr-cli"
          - "fedora-packager"
          - "mock"
          - "mock-centos-sig-configs"
          - "mock-core-configs"
          - "rpm-build"
          - "rpmdevtools"
          - "rpmlint"
        state: "latest"
      tags:
        - "dnf"

    - name: Configure unprivileged access to Mock for {{ ansible_ssh_user }}
      ansible.builtin.user:
        name: "{{ ansible_ssh_user }}"
        groups: mock
        append: yes
      tags:
        - "user"
