##
 # Author: Neal Gompa
 #
 # Licensed under the GNU General Public License Version 3
 # Fedora-License-Identifier: GPLv3+
 # SPDX-2.0-License-Identifier: GPL-3.0+
 # SPDX-3.0-License-Identifier: GPL-3.0-or-later
 #
 # This is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this.  If not, see <https://www.gnu.org/licenses/>.
##


---
- name: Install and configure common development software
  become: true
  block:
   - name: Install basic development tools
     ansible.builtin.dnf:
       pkg:
         - "colordiff"
         - "emacs-ansible"
         - "emacs-blacken"
         - "emacs-color-theme"
         - "emacs-dockerfile-mode"
         - "emacs-json-mode"
         - "emacs-nox"
         - "clang-tools-extra" # C/C++ LSP server
         - "gcc-c++"
         - "git"
         - "git-lfs"
         - "git-email"
         - "gh" # GitHub's CLI tool
         - "glab" # GitLab's CLI tool
         - "nano"
         - "pag" # Pagure's CLI tool
         - "podman" # For OCI containers
         - "poetry"
         - "python3"
         - "python3-lsp-black"
         - "python3-lsp-server"
         - "systemd-container" # For OS containers using nspawn
       state: "present"
     tags:
       - "dnf"
