##
 # Author: Neal Gompa
 #
 # Licensed under the GNU General Public License Version 3
 # Fedora-License-Identifier: GPLv3+
 # SPDX-2.0-License-Identifier: GPL-3.0+
 # SPDX-3.0-License-Identifier: GPL-3.0-or-later
 #
 # This is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this.  If not, see <https://www.gnu.org/licenses/>.
##


---
- name: Run tasks for Fedora
  include_tasks: kde-fedora.yml
  when: ansible_facts["distribution"] == "Fedora"

- name: Configure the KDE Plasma desktop
  block:
   - name: Set KWin to four virtual desktops in a grid
     ansible.builtin.shell: |
       kwriteconfig5 --file kwinrc --group Desktops --key Number 4
       kwriteconfig5 --file kwinrc --group Desktops --key Rows 2
     tags:
       - "kwin"
   - name: Set KWin to respond to keyboard shortcuts to navigate virtual desktops
     ansible.builtin.shell: |
       kwriteconfig5 --file kglobalshortcutsrc --group kwin --key 'Switch One Desktop Down' 'Meta+Ctrl+Down,Meta+Ctrl+Down,Switch One Desktop Down'
       kwriteconfig5 --file kglobalshortcutsrc --group kwin --key 'Switch One Desktop Up' 'Meta+Ctrl+Up,Meta+Ctrl+Up,Switch One Desktop Up'
       kwriteconfig5 --file kglobalshortcutsrc --group kwin --key 'Switch One Desktop to the Left' 'Meta+Ctrl+Left,Meta+Ctrl+Left,Switch One Desktop to the Left'
       kwriteconfig5 --file kglobalshortcutsrc --group kwin --key 'Switch One Desktop to the Right' 'Meta+Ctrl+Right,Meta+Ctrl+Right,Switch One Desktop to the Right'
     tags:
       - "kwin"
   - name: Set KWin to use the thumbnail grid tab switcher
     ansible.builtin.command: "kwriteconfig5 --file kwinrc --group TabBox --key LayoutName thumbnail_grid"
     tags:
       - "kwin"
   - name: Set KWin to enable Night Color
     ansible.builtin.shell: |
       kwriteconfig5 --file kwinrc --group NightColor --key Active true
       kwriteconfig5 --file kwinrc --group NightColor --key DayTemperature 5000
       kwriteconfig5 --file kwinrc --group NightColor --key NightTemperature 3000
     tags:
       - "kwin"
   - name: Set up KWin plugins
     ansible.builtin.shell: |
       kwriteconfig5 --file kwinrc --group Plugins --key desktopchangeosdEnabled true
       kwriteconfig5 --file kwinrc --group Plugins --key glideEnabled true
       kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_scaleEnabled false
       kwriteconfig5 --file kwinrc --group Plugins --key sheetEnabled true
     tags:
       - "kwin"
   - name: Set KWin to enable wobbly windows
     ansible.builtin.shell: |
       kwriteconfig5 --file kwinrc --group Plugins --key wobblywindowsEnabled true
       kwriteconfig5 --file kwinrc --group Effect-wobblywindows --key Drag 92
       kwriteconfig5 --file kwinrc --group Effect-wobblywindows --key MoveFactor 20
       kwriteconfig5 --file kwinrc --group Effect-wobblywindows --key Stiffness 3
       kwriteconfig5 --file kwinrc --group Effect-wobblywindows --key WobblynessLevel 3
     tags:
       - "kwin"
   - name: Set KUserFeedback to enable anonymous user feedback
     ansible.builtin.command: "kwriteconfig5 --file PlasmaUserFeedback --group Global --key FeedbackLevel 64"
     tags:
       - "kuserfeedback"

- name: Install extra applications for KDE
  become: true
  block:
   - name: Install KDE app and support packages
     ansible.builtin.dnf:
       pkg:
         - "kjournald"
         - "neochat"
       state: "present"
     tags:
       - "dnf"
