##
 # Author: Neal Gompa
 #
 # Licensed under the GNU General Public License Version 3
 # Fedora-License-Identifier: GPLv3+
 # SPDX-2.0-License-Identifier: GPL-3.0+
 # SPDX-3.0-License-Identifier: GPL-3.0-or-later
 #
 # This is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this.  If not, see <https://www.gnu.org/licenses/>.
##


---
- name: Gather RPM package manager package facts
  ansible.builtin.package_facts:
    manager:
     - "rpm"

- name: Run tasks for CentOS/RHEL
  include_tasks: centos.yml
  when: ansible_facts["distribution"] == "CentOS"

- name: Run tasks for Fedora
  include_tasks: fedora.yml
  when: ansible_facts["distribution"] == "Fedora"

- name: Install Tailscale
  become: true
  block:
   - name: Install Tailscale
     ansible.builtin.dnf:
       pkg:
         - "tailscale"
       state: "latest"
     tags:
       - "tailscale"
       - "dnf"
   - name: Enable Tailscale service
     ansible.builtin.systemd:
        name: "tailscaled.service"
        state: started
        enabled: true
     tags:
       - "tailscale"
       - "systemd"
   - name: Activate Tailscale
     ansible.builtin.command: "tailscale up --authkey {{ tailscale_auth_key }}"
     when: tailscale_auth_key is defined
     tags:
       - "tailscale"

- name: Install and configure common base software
  become: true
  block:
   - name: Install basic tools
     ansible.builtin.dnf:
       pkg:
         - "ansible"
         - "below"
         - "fish"
         - "git-core"
         - "htop"
         - "lm_sensors"
       state: "present"
     tags:
       - "dnf"
   - name: Configure {{ ansible_ssh_user }} to use fish shell
     ansible.builtin.user:
       name: "{{ ansible_ssh_user }}"
       shell: /bin/fish
     tags:
       - "user"
