##
 # Author: Neal Gompa
 #
 # Licensed under the GNU General Public License Version 3
 # Fedora-License-Identifier: GPLv3+
 # SPDX-2.0-License-Identifier: GPL-3.0+
 # SPDX-3.0-License-Identifier: GPL-3.0-or-later
 #
 # This is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this.  If not, see <https://www.gnu.org/licenses/>.
##


---
- name: Prepare system for building images
  become: true
  block:
    - name: Install image build tools
      ansible.builtin.dnf:
        pkg:
          - "appliance-tools"
          - "kiwi-cli"
          - "livecd-tools"
          - "pykickstart"
        state: "latest"
      tags:
        - "dnf"
    - name: Configure sudoers to allow {{ ansible_ssh_user }} to build images
      community.general.sudoers:
        name: allow-imgbuildtools
        state: present
        user: "{{ ansible_ssh_user }}"
        commands:
          - /usr/bin/appliance-creator
          - /usr/bin/livecd-creator
          - /usr/bin/kiwi
          - /usr/bin/kiwi-ng
        nopassword: true
      tags:
        - "user"
        - "sudo"
